/* Generated By:JavaCC: Do not edit this line. DockerfileConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface DockerfileConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int COM = 4;
  /** RegularExpression Id. */
  int COMANDO = 5;
  /** RegularExpression Id. */
  int CADENA = 6;
  /** RegularExpression Id. */
  int BACK = 7;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "<COM>",
    "<COMANDO>",
    "<CADENA>",
    "<BACK>",
  };

}
