/* Generated By:JavaCC: Do not edit this line. DockerfileConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface DockerfileConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int COMANDO = 1;
  /** RegularExpression Id. */
  int EOL = 2;
  /** RegularExpression Id. */
  int OTRO = 3;
  /** RegularExpression Id. */
  int COGER_COMANDO = 4;
  /** RegularExpression Id. */
  int IGNORAR_ESPACIO = 5;
  /** RegularExpression Id. */
  int IGNORAR_COSAS = 6;
  /** RegularExpression Id. */
  int SALTO_LINEA = 7;
  /** RegularExpression Id. */
  int COGER_COMANDOS = 8;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int ESPACIO = 1;
  /** Lexical state. */
  int COSAS = 2;
  /** Lexical state. */
  int SALTO = 3;
  /** Lexical state. */
  int COMANDOS = 4;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<COMANDO>",
    "\"\\n\"",
    "<OTRO>",
    "<COGER_COMANDO>",
    "<IGNORAR_ESPACIO>",
    "<IGNORAR_COSAS>",
    "<SALTO_LINEA>",
    "<COGER_COMANDOS>",
  };

}
